services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile.api
    image: react-flask-app-api
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: react-flask-app-client
    ports:
      - "3000:80"